### PR TITLE
Tandem hunter app dev

### PR DESCRIPTION
**Pull request by nadia31415**
Adapted TandemHunter tool to DNAnexus app 
App testing documented in https://cuhbioinformatics.atlassian.net/wiki/spaces/UTILS/pages/2742976542/Building+TandemHunter+app

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tandem_hunter/3)

### CODE REVIEW

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 21 of 24 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tandem_hunter/3)* status: 23 of 24 files reviewed, 7 unresolved discussions (waiting on @nadia31415 and @oniblock)

___
*[`dxapp.json` line 19 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tandem_hunter/3#-NEWxO3I08Q8Io_wWNYz:-NEWxO3I08Q8Io_wWNZ-:ble9lst) ([raw file](https://github.com/eastgenomics/eggd_tandem_hunter/blob/037db28031350cc5bdacd42977e0fe8ac7a05276/dxapp.json#L19)):*
> ```JSON
>       "name": "coverage_files",
>       "label": "Query coverage_file/s",
>       "help": "Per target coverage file containing exon coordinates and normalised coverage values (pertarget_coverage.tsv)",
> ```

file(s)



_Code quote:_
```JSON
file
```
___
*[`dxapp.json` line 40 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tandem_hunter/3#-NEWxXVa4ALFOyqBLWxS:-NEWxXVa4ALFOyqBLWxT:b-ikebl1) ([raw file](https://github.com/eastgenomics/eggd_tandem_hunter/blob/037db28031350cc5bdacd42977e0fe8ac7a05276/dxapp.json#L40)):*
> ```JSON
>     },
>     {
>       "name": "run",
> ```

Does this have to be the run name, or is it just whatever prefix you want added to the output filename?

If the latter, consider renaming (e.g. `output_prefix`



_Code quote:_
```JSON
run
```
___
*[`src/code.sh` line 14 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tandem_hunter/3#-NEWuxUu14JMKFAqVQ4w:-NEWuxUv2hg6Pbz3DJwk:bd81gpr) ([raw file](https://github.com/eastgenomics/eggd_tandem_hunter/blob/037db28031350cc5bdacd42977e0fe8ac7a05276/src/code.sh#L14)):*
> ```Shell
> #pip3 install /pytz-*.whl /numpy-*.whl /pandas-*.whl
> pip3 install pandas==1.1.3 #fix, should be installed from file
> pip3 install openpyxl
> ```

Can these be installed from the python packages asset you have included?



_Code quote:_
```Shell
pip3 install pandas==1.1.3 #fix, should be installed from file
pip3 install openpyxl
```
___
*[`src/code.sh` line 28 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tandem_hunter/3#-NEWwIu61TYASibiaZD-:-NEWwIu61TYASibiaZD0:b-6xcuh5) ([raw file](https://github.com/eastgenomics/eggd_tandem_hunter/blob/037db28031350cc5bdacd42977e0fe8ac7a05276/src/code.sh#L28)):*
> ```Shell
> echo "Tandemhunter_test"
> python3 TandemHunter.py -h
> echo "test_complete"
> ```

Is this for debugging? Should it be removed now?



_Code quote:_
```Shell
echo "Tandemhunter_test"
python3 TandemHunter.py -h
echo "test_complete"
```
___
*[`src/code.sh` line 31 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tandem_hunter/3#-NEWw_IK6uE8wnTqLjx2:-NEWw_IK6uE8wnTqLjx3:bx7q30a) ([raw file](https://github.com/eastgenomics/eggd_tandem_hunter/blob/037db28031350cc5bdacd42977e0fe8ac7a05276/src/code.sh#L31)):*
> ```Shell
> python3 TandemHunter.py -B /home/dnanexus/in/coverage_files/ --intervals /home/dnanexus/in/intervals/* -O /home/dnanexus/out/comparison_csv $advanced_options
> echo "tandemhunter_done"
> # Run second script (if number of files greater than 1)
> ```

Does this still apply, or do you always run the second script?



_Code quote:_
```Shell
# Run second script (if number of files greater than 1)
```
___
*[`src/code.sh` line 33 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tandem_hunter/3#-NEWwg5J6Q1Fgx3fzmKy:-NEWwg5K1igLOGKmWmax:bhn64t2) ([raw file](https://github.com/eastgenomics/eggd_tandem_hunter/blob/037db28031350cc5bdacd42977e0fe8ac7a05276/src/code.sh#L33)):*
> ```Shell
> # Run second script (if number of files greater than 1)
> # collate data into single dataframe
> #if f in ["$coverage_targets_file"]>1 ; then
> ```

Remove if not used



_Code quote:_
```Shell
if f in ["$coverage_targets_file"]>1 ; then
```
___
*[`resources/home/dnanexus/inputs/intervals_b38.json` line 10 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tandem_hunter/3#-NEWx7Ha49TvQNj_mke-:-NEWx7Ha49TvQNj_mke0:b-ewp2cc) ([raw file](https://github.com/eastgenomics/eggd_tandem_hunter/blob/037db28031350cc5bdacd42977e0fe8ac7a05276/resources/home/dnanexus/inputs/intervals_b38.json#L10)):*
> ```JSON
>       },
>       "region2":{
>          "chrom":"chr11",
> ```

Do we definitely want chrs here?



_Code quote:_
```JSON
chr
```

**Review by nadia31415 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tandem_hunter/3)* status: 22 of 24 files reviewed, 7 unresolved discussions (waiting on @mattgarner and @oniblock)

___
*[`dxapp.json` line 19 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tandem_hunter/3#-NEWxO3I08Q8Io_wWNYz:-NE_I58iAtvcAIxzVpfx:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_tandem_hunter/blob/037db28031350cc5bdacd42977e0fe8ac7a05276/dxapp.json#L19)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

file(s)
</blockquote></details>

Done.
___
*[`dxapp.json` line 40 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tandem_hunter/3#-NEWxXVa4ALFOyqBLWxS:-NE_INY175NVKEryGWQb:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_tandem_hunter/blob/037db28031350cc5bdacd42977e0fe8ac7a05276/dxapp.json#L40)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Does this have to be the run name, or is it just whatever prefix you want added to the output filename?

If the latter, consider renaming (e.g. `output_prefix`
</blockquote></details>

Done.
___
*[`src/code.sh` line 14 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tandem_hunter/3#-NEWuxUu14JMKFAqVQ4w:-NE_J6GG7AZRn4NdG1UC:bw4lenm) ([raw file](https://github.com/eastgenomics/eggd_tandem_hunter/blob/037db28031350cc5bdacd42977e0fe8ac7a05276/src/code.sh#L14)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Can these be installed from the python packages asset you have included?
</blockquote></details>

The app failed during testing when installing python packages assets alone, likely due to a different version of pandas. Pandas 1.1.3 specifically needs to be installed for tool to work at the moment. 
___
*[`src/code.sh` line 28 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tandem_hunter/3#-NEWwIu61TYASibiaZD-:-NE_K0uo0xfvJCFrZCh0:b-hfpv0l) ([raw file](https://github.com/eastgenomics/eggd_tandem_hunter/blob/037db28031350cc5bdacd42977e0fe8ac7a05276/src/code.sh#L28)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Is this for debugging? Should it be removed now?
</blockquote></details>

removed
___
*[`src/code.sh` line 31 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tandem_hunter/3#-NEWw_IK6uE8wnTqLjx2:-NE_K8dA5rgAzWcE4YZx:b-towf7) ([raw file](https://github.com/eastgenomics/eggd_tandem_hunter/blob/037db28031350cc5bdacd42977e0fe8ac7a05276/src/code.sh#L31)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Does this still apply, or do you always run the second script?
</blockquote></details>

removed, xls generated regardless of number of files 
___
*[`src/code.sh` line 33 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tandem_hunter/3#-NEWwg5J6Q1Fgx3fzmKy:-NE_KN9P106-yrmtFCSN:b-hfpv0l) ([raw file](https://github.com/eastgenomics/eggd_tandem_hunter/blob/037db28031350cc5bdacd42977e0fe8ac7a05276/src/code.sh#L33)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Remove if not used
</blockquote></details>

removed
___
*[`resources/home/dnanexus/inputs/intervals_b38.json` line 10 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tandem_hunter/3#-NEWx7Ha49TvQNj_mke-:-NE_IQ0o4ij_cnspOmTK:bp1zocx) ([raw file](https://github.com/eastgenomics/eggd_tandem_hunter/blob/037db28031350cc5bdacd42977e0fe8ac7a05276/resources/home/dnanexus/inputs/intervals_b38.json#L10)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Do we definitely want chrs here?
</blockquote></details>

The input file is the output from eggd_Picard e.g. project-GBvqkQ04JqfJGy2J5783Qjkk:file-GG72xJQ40907PGpJJVkqY1V0. These files have 'chr' prefix

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tandem_hunter/3)* status: all files reviewed, 4 unresolved discussions (waiting on @nadia31415 and @oniblock)

___
*[`dxapp.json` line 40 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tandem_hunter/3#-NEWxXVa4ALFOyqBLWxS:-NFNL5Ev7Q88Z7c8zuNG:b-wz1pcg) ([raw file](https://github.com/eastgenomics/eggd_tandem_hunter/blob/037db28031350cc5bdacd42977e0fe8ac7a05276/dxapp.json#L40)):*
<details><summary><i>Previously, nadia31415 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Should label and help be updated accordingly?
___
*[`src/code.sh` line 14 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tandem_hunter/3#-NEWuxUu14JMKFAqVQ4w:-NFNLgGdB5-6H7S7WRZV:b-epc6zk) ([raw file](https://github.com/eastgenomics/eggd_tandem_hunter/blob/037db28031350cc5bdacd42977e0fe8ac7a05276/src/code.sh#L14)):*
<details><summary><i>Previously, nadia31415 wrote…</i></summary><blockquote>

The app failed during testing when installing python packages assets alone, likely due to a different version of pandas. Pandas 1.1.3 specifically needs to be installed for tool to work at the moment. 
</blockquote></details>

You can get the 1.1.3 tarball here:
https://github.com/pandas-dev/pandas/releases/tag/v1.1.3

which can be included with the app, then you can install it from that
___
*[`src/code.sh` line 28 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tandem_hunter/3#-NEWwIu61TYASibiaZD-:-NFNLvrz3V9H6n4ON1FT:bhqdtrp) ([raw file](https://github.com/eastgenomics/eggd_tandem_hunter/blob/037db28031350cc5bdacd42977e0fe8ac7a05276/src/code.sh#L28)):*
<details><summary><i>Previously, nadia31415 wrote…</i></summary><blockquote>

removed
</blockquote></details>

The echos before and after seem redundant now that this has been removed. Should they be removed too?

**Review by nadia31415 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tandem_hunter/3)* status: 22 of 24 files reviewed, 4 unresolved discussions (waiting on @mattgarner and @oniblock)

___
*[`dxapp.json` line 40 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tandem_hunter/3#-NEWxXVa4ALFOyqBLWxS:-NFNRNN28kqE2XdwAZO2:bgm43md) ([raw file](https://github.com/eastgenomics/eggd_tandem_hunter/blob/037db28031350cc5bdacd42977e0fe8ac7a05276/dxapp.json#L40)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Should label and help be updated accordingly?
</blockquote></details>

changed label and help message for output prefix argument
___
*[`src/code.sh` line 14 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tandem_hunter/3#-NEWuxUu14JMKFAqVQ4w:-NFOD8DcD-eXrXSi4bcE:b-wemmbq) ([raw file](https://github.com/eastgenomics/eggd_tandem_hunter/blob/037db28031350cc5bdacd42977e0fe8ac7a05276/src/code.sh#L14)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

You can get the 1.1.3 tarball here:
https://github.com/pandas-dev/pandas/releases/tag/v1.1.3

which can be included with the app, then you can install it from that
</blockquote></details>

Recommended to pip download specific version of pandas (before pip install)



_Code snippet:_
```Shell
pip download pandas==1.1.3
```
___
*[`src/code.sh` line 28 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tandem_hunter/3#-NEWwIu61TYASibiaZD-:-NFNSXBZ9-iUWQvjsVar:b9psxak) ([raw file](https://github.com/eastgenomics/eggd_tandem_hunter/blob/037db28031350cc5bdacd42977e0fe8ac7a05276/src/code.sh#L28)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

The echos before and after seem redundant now that this has been removed. Should they be removed too?
</blockquote></details>

removed echo statements when running tandemhunter tool

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tandem_hunter/3)* status: all files reviewed, 1 unresolved discussion (waiting on @nadia31415 and @oniblock)

___
*[`src/code.sh` line 14 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tandem_hunter/3#-NEWuxUu14JMKFAqVQ4w:-NFSUBkFB_yuxy4f409p:b8t7if) ([raw file](https://github.com/eastgenomics/eggd_tandem_hunter/blob/037db28031350cc5bdacd42977e0fe8ac7a05276/src/code.sh#L14)):*
<details><summary><i>Previously, nadia31415 wrote…</i></summary><blockquote>

Recommended to pip download specific version of pandas (before pip install)
</blockquote></details>

I think the guidance in egg-overflow has been slightly misunderstood. You should do the pip3 download outside the app (e.g. on your laptop) to get the files to include in the app, then add those files to the app resources and install from those files within the app.

The aim is do eliminate external dependencies (in this case downloading the package from somewhere externally hosted) at runtime.

**Review by nadia31415 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tandem_hunter/3)* status: 23 of 29 files reviewed, 1 unresolved discussion (waiting on @mattgarner and @oniblock)

___
*[`src/code.sh` line 14 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tandem_hunter/3#-NEWuxUu14JMKFAqVQ4w:-NFSeW_-E3k6i8-2-Q6I:bam1icc) ([raw file](https://github.com/eastgenomics/eggd_tandem_hunter/blob/037db28031350cc5bdacd42977e0fe8ac7a05276/src/code.sh#L14)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

I think the guidance in egg-overflow has been slightly misunderstood. You should do the pip3 download outside the app (e.g. on your laptop) to get the files to include in the app, then add those files to the app resources and install from those files within the app.

The aim is do eliminate external dependencies (in this case downloading the package from somewhere externally hosted) at runtime.
</blockquote></details>

apologies, so I downloaded pandas 1.1.3 and dependencies locally, put files in resources directory and now pip install using .whl files

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tandem_hunter/3)* status: 23 of 29 files reviewed, 2 unresolved discussions (waiting on @mattgarner, @nadia31415, and @woook)

___
*[`src/code.sh` line 13 at r7](https://reviewable.io/reviews/eastgenomics/eggd_tandem_hunter/3#-NPwetnK2-9VUkkBLHXy:-NPwetnK2-9VUkkBLHXz:bmm7nw6) ([raw file](https://github.com/eastgenomics/eggd_tandem_hunter/blob/d0356916c52f550a0e88f0a97e3bac88d298408f/src/code.sh#L13)):*
> ```Shell
> # Install packages from the python asset
> #pip3 install /pytz-*.whl /numpy-*.whl /pandas-*.whl
> pip3 install numpy-1.23.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
> ```

this can be shortened to install all wheel files in a given `packages` directory with:
```
python3 -m pip install -q --no-index --no-deps  packages/*
```

keeping all required python wheel / tar files in a single packages directory is cleaner and lets you install in one line and doesn't require you to specify each package

example here: https://github.com/eastgenomics/eggd_conductor/tree/main/resources/home/dnanexus/packages



_Code quote:_
```Shell
pip3 install numpy-1.23.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
pip3 install pandas-1.1.3-cp38-cp38-manylinux1_x86_64.whl
pip3 install python_dateutil-2.8.2-py2.py3-none-any.whl
pip3 install pytz-2022.5-py2.py3-none-any.whl
pip3 install six-1.16.0-py2.py3-none-any.whl
pip3 install openpyxl
```

**Review by nadia31415 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tandem_hunter/3)* status: 23 of 29 files reviewed, 2 unresolved discussions (waiting on @jethror1, @mattgarner, and @woook)

___
*[`src/code.sh` line 13 at r7](https://reviewable.io/reviews/eastgenomics/eggd_tandem_hunter/3#-NPwetnK2-9VUkkBLHXy:-NQ-QD_3BC6lUjyVegz6:b-pvkvrs) ([raw file](https://github.com/eastgenomics/eggd_tandem_hunter/blob/d0356916c52f550a0e88f0a97e3bac88d298408f/src/code.sh#L13)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

this can be shortened to install all wheel files in a given `packages` directory with:
```
python3 -m pip install -q --no-index --no-deps  packages/*
```

keeping all required python wheel / tar files in a single packages directory is cleaner and lets you install in one line and doesn't require you to specify each package

example here: https://github.com/eastgenomics/eggd_conductor/tree/main/resources/home/dnanexus/packages
</blockquote></details>

Have moved packages to separate dir and shortened installation command

**Review by jethror1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tandem_hunter/3)* status: 23 of 29 files reviewed, 1 unresolved discussion (waiting on @mattgarner and @woook)

**Comment by woook** [comment]
Hi @nadia31415 - I'm a bit apprenhensive about doing a code review as I can see that others have started that already - shouldn't one of them finish now that they've started?

**Review by Jay-Miles — APPROVED** [review]
> Reviewed 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tandem_hunter/3)* status: all files reviewed, 1 unresolved discussion (waiting on @mattgarner)

**Review by mattgarner — APPROVED** [review]
> Reviewed 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tandem_hunter/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nadia31415)

**Pull request merged**
